name: Check for "do-not-merge" label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened]

jobs:
  check_do_not_merge_label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create "do-not-merge" Label
        id: create_label
        if: contains(github.event.pull_request.title, 'New Crowdin updates')
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh label create do-not-merge --description "A PR with this label should not be merged" --color CC0202  --force
      - name: Add "do-not-merge" Label to Crowdin update PR
        id: add_label
        if: contains(github.event.pull_request.title, 'New Crowdin updates')
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label do-not-merge
      - name: Check for "do-not-merge" Label
        id: check_label
        # https://stackoverflow.com/a/71510189/992102
        if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
        run: |
          echo "Failed to retrieve PR labels."
          exit 1
