name: Check for "do-not-merge" label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened]

jobs:
  check_do_not_merge_label:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "do-not-merge" Label
        id: check_label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')

          if [[ $? -ne 0 ]]; then
            echo "Failed to retrieve PR labels."
            exit 1
          fi

          if echo "$labels" | grep -qw do-not-merge; then
            echo "DO NOT MERGE"
            exit 1
          fi
