name: Sync Translations
on:
  # schedule:
  #   - cron: '0 12 * * WED'  # Every Wednesday at midnight
  workflow_dispatch:
jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Scipy translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          crowdin-project: "scipy.org"
          source-repo: "scipy/scipy.org"
          source-path: "content/en/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/scipy.org-translations"
          translations-path: "content/"
          translations-source-path: "content/en/"
          translations-ref: "main"
          translation-percentage: "90"
          approval-percentage: "0"
          use-precommit: "true"
          create-toml-file: "true"
          create-upstream-pr: "true"
          auto-merge: "false"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
          crowdin-token: ${{ secrets.CROWDIN_TOKEN }}
